services:
  express:
    build: src/backend
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_DATABASE
networks:
  default:
    ipam:
      config:
        - subnet: 10.108.0.0/14