services:
  frontend:
    build: nginx
    ports:
      - 80:80
  backend:
    build: src/backend
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
      - STREAM_API_KEY=${STREAM_API_KEY}
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - ADMIN_ID=${ADMIN_ID}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodata:/data/db
networks:
  default:
    ipam:
      config:
        - subnet: 10.108.0.0/14
volumes:
  mongodata: