import { User } from "../user/types.js";

export const mockUser1: User = {
  uid: "1",
  chatToken: "test",
  notificationToken: "",
  idToken: "",
  email: "rubendewitte1998@gmail.com",
  completedRegistration: true,
  countryCode: "+49",
  phoneNumber: "17647121329",
  firstName: "Ruben",
  birthdate: "2000-01-01T00:00:00.000Z", // Age ~24 years
  gender: "man",
  mode: "dating",
  images: [
    "https://firebasestorage.googleapis.com/v0/b/pssd-app.appspot.com/o/75mhuQKLmOPI1yFJxYJH9vNF63l1%2Fimages%2F6e8a488e-17b3-4e6b-9899-7ea5a826857b-colajpg?alt=media&token=89dc5c23-584c-4348-9061-18fbecb3a1e7",
  ],
  preferences: {
    genderPreference: "women",
    ageStart: 18,
    ageEnd: 100,
    showAge: true,
    maxDistance: 100,
    global: true,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: { school: "", jobTitle: "", about: "", company: "", city: "" },
  pssd: { duration: "3to5years", symptoms: [], medications: [] },
  location: {
    coordinates: [8.7500944, 50.1083114],
    type: "Point",
  },
};

export const mockUser2: User = {
  uid: "2",
  chatToken: "test",
  notificationToken: "",
  idToken: "",
  email: "bobientje+2@gmail.com",
  completedRegistration: true,
  countryCode: "+49",
  phoneNumber: "17647121329",
  firstName: "Bobientje2",
  birthdate: "1998-05-15T00:00:00.000Z", // Age ~26 years
  gender: "woman",
  mode: "dating",
  images: [
    "https://firebasestorage.googleapis.com/v0/b/pssd-app.appspot.com/o/75mhuQKLmOPI1yFJxYJH9vNF63l1%2Fimages%2F6e8a488e-17b3-4e6b-9899-7ea5a826857b-colajpg?alt=media&token=89dc5c23-584c-4348-9061-18fbecb3a1e7",
  ],
  preferences: {
    genderPreference: "men",
    ageStart: 18,
    ageEnd: 40,
    showAge: true,
    maxDistance: 20,
    global: true,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: { school: "", jobTitle: "", about: "", company: "", city: "" },
  pssd: { duration: "3to5years", symptoms: [], medications: [] },
  location: {
    coordinates: [8.7500944, 50.54740168377306],
    type: "Point",
  },
};

export const mockUser3: User = {
  uid: "3",
  chatToken: "sampleToken3",
  idToken: "",
  notificationToken: "",
  email: "johnsmith@example.com",
  completedRegistration: true,
  countryCode: "+44",
  phoneNumber: "447987654321",
  firstName: "John",
  birthdate: "1999-11-20T00:00:00.000Z", // Age ~24 years
  gender: "man",
  mode: "friends",
  images: ["https://example.com/images/john.jpg"],
  preferences: {
    genderPreference: "women",
    ageStart: 18,
    ageEnd: 45,
    showAge: false,
    maxDistance: 200,
    global: true,
    showDistance: true,
    showMe: false,
  },
  registrationInProgress: false,
  profile: {
    school: "",
    jobTitle: "Marketing Specialist",
    about: "Enjoys hiking and photography.",
    company: "MarketingPro",
    city: "London",
  },
  pssd: { duration: "6to12months", symptoms: ["anxiety"], medications: ["sertraline"] },
  location: {
    coordinates: [2.352222, 48.856613],
    type: "Point",
  },
};

export const mockUser4: User = {
  uid: "4",
  chatToken: "sampleToken4",
  idToken: "",
  notificationToken: "",
  email: "alice@example.com",
  completedRegistration: true,
  countryCode: "+33",
  phoneNumber: "33612345678",
  firstName: "Alice",
  birthdate: "1997-04-10T00:00:00.000Z", // Age ~27 years
  gender: "woman",
  mode: "networking",
  images: ["https://example.com/images/alice.jpg"],
  preferences: {
    genderPreference: "men",
    ageStart: 18,
    ageEnd: 50,
    showAge: true,
    maxDistance: 150,
    global: false,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "Paris University",
    jobTitle: "Designer",
    about: "Passionate about art and design.",
    company: "ArtHouse",
    city: "Paris",
  },
  pssd: { duration: "6to12months", symptoms: ["insomnia"], medications: ["fluoxetine"] },
  location: {
    coordinates: [2.352222, 48.856613],
    type: "Point",
  },
};

export const mockUser5: User = {
  uid: "5",
  chatToken: "sampleToken5",
  idToken: "",
  notificationToken: "",
  email: "michael@example.com",
  completedRegistration: true,
  countryCode: "+61",
  phoneNumber: "61412345678",
  firstName: "Michael",
  birthdate: "1996-09-30T00:00:00.000Z", // Age ~28 years
  gender: "man",
  mode: "dating",
  images: ["https://example.com/images/michael.jpg"],
  preferences: {
    genderPreference: "women",
    ageStart: 18,
    ageEnd: 40,
    showAge: true,
    maxDistance: 80,
    global: true,
    showDistance: false,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "",
    jobTitle: "Engineer",
    about: "Loves to travel and explore new places.",
    company: "Engineers Inc",
    city: "Sydney",
  },
  pssd: {
    duration: "3to5years",
    symptoms: ["low libido"],
    medications: ["escitalopram"],
  },
  location: {
    coordinates: [151.209296, -33.86882],
    type: "Point",
  },
};

export const mockUser6: User = {
  uid: "6",
  chatToken: "sampleToken6",
  idToken: "",
  notificationToken: "",
  email: "emily@example.com",
  completedRegistration: true,
  countryCode: "+34",
  phoneNumber: "34912345678",
  firstName: "Emily",
  birthdate: "1997-07-12T00:00:00.000Z", // Age ~26 years
  gender: "woman",
  mode: "networking",
  images: ["https://example.com/images/emily.jpg"],
  preferences: {
    genderPreference: "women",
    ageStart: 18,
    ageEnd: 35,
    showAge: true,
    maxDistance: 60,
    global: true,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "Barcelona University",
    jobTitle: "Consultant",
    about: "Enthusiastic about business and technology.",
    company: "ConsultPro",
    city: "Barcelona",
  },
  pssd: { duration: "3to5years", symptoms: ["headaches"], medications: ["citalopram"] },
  location: {
    coordinates: [2.173404, 41.385063],
    type: "Point",
  },
};

export const mockUser7: User = {
  uid: "7",
  chatToken: "sampleToken7",
  idToken: "",
  notificationToken: "",
  email: "david@example.com",
  completedRegistration: true,
  countryCode: "+1",
  phoneNumber: "14081234567",
  firstName: "David",
  birthdate: "1995-11-18T00:00:00.000Z", // Age ~28 years
  gender: "man",
  mode: "dating",
  images: ["https://example.com/images/david.jpg"],
  preferences: {
    genderPreference: "women",
    ageStart: 18,
    ageEnd: 50,
    showAge: true,
    maxDistance: 30,
    global: false,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "University of California",
    jobTitle: "Entrepreneur",
    about: "Running my own tech startup.",
    company: "StartUp Inc",
    city: "San Francisco",
  },
  pssd: {
    duration: "morethan10years",
    symptoms: ["depression"],
    medications: ["venlafaxine"],
  },
  location: {
    coordinates: [-122.419418, 37.774929],
    type: "Point",
  },
};

export const mockUser8: User = {
  uid: "8",
  chatToken: "sampleToken8",
  idToken: "",
  notificationToken: "",
  email: "sarah@example.com",
  completedRegistration: true,
  countryCode: "+1",
  phoneNumber: "16041234567",
  firstName: "Sarah",
  birthdate: "1998-02-01T00:00:00.000Z", // Age ~26 years
  gender: "woman",
  mode: "friends",
  images: ["https://example.com/images/sarah.jpg"],
  preferences: {
    genderPreference: "men",
    ageStart: 18,
    ageEnd: 40,
    showAge: false,
    maxDistance: 100,
    global: true,
    showDistance: false,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "University of Toronto",
    jobTitle: "Data Scientist",
    about: "Data enthusiast and book lover.",
    company: "DataCorp",
    city: "Toronto",
  },
  pssd: { duration: "1to2years", symptoms: ["dizziness"], medications: ["paroxetine"] },
  location: {
    coordinates: [-79.347015, 43.65107],
    type: "Point",
  },
};

export const mockUser9: User = {
  uid: "9",
  chatToken: "sampleToken9",
  idToken: "",
  notificationToken: "",
  email: "chris@example.com",
  completedRegistration: true,
  countryCode: "+81",
  phoneNumber: "81312345678",
  firstName: "Chris",
  birthdate: "2000-09-05T00:00:00.000Z", // Age ~24 years
  gender: "man",
  mode: "networking",
  images: ["https://example.com/images/chris.jpg"],
  preferences: {
    genderPreference: "everyone",
    ageStart: 18,
    ageEnd: 30,
    showAge: true,
    maxDistance: 20,
    global: false,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "Tokyo University",
    jobTitle: "Researcher",
    about: "Interested in AI and robotics.",
    company: "TechLab",
    city: "Tokyo",
  },
  pssd: { duration: "1to2years", symptoms: ["headaches"], medications: ["fluoxetine"] },
  location: {
    coordinates: [139.691711, 35.689487],
    type: "Point",
  },
};

export const mockUser10: User = {
  uid: "10",
  chatToken: "sampleToken10",
  idToken: "",
  notificationToken: "",
  email: "samantha@example.com",
  completedRegistration: true,
  countryCode: "+44",
  phoneNumber: "441234567890",
  firstName: "Samantha",
  birthdate: "1998-12-11T00:00:00.000Z", // Age ~25 years
  gender: "woman",
  mode: "dating",
  images: ["https://example.com/images/samantha.jpg"],
  preferences: {
    genderPreference: "men",
    ageStart: 18,
    ageEnd: 50,
    showAge: true,
    maxDistance: 1000,
    global: false,
    showDistance: true,
    showMe: true,
  },
  registrationInProgress: false,
  profile: {
    school: "",
    jobTitle: "Physician",
    about: "Caring and compassionate.",
    company: "HealthCare Plus",
    city: "Manchester",
  },
  pssd: {
    duration: "3to5years",
    symptoms: ["low libido"],
    medications: ["escitalopram"],
  },
  location: {
    coordinates: [-2.242631, 53.480759],
    type: "Point",
  },
};

export const mockUsers: User[] = [
  mockUser1,
  mockUser2,
  mockUser3,
  mockUser4,
  mockUser5,
  mockUser6,
  mockUser7,
  mockUser8,
  mockUser9,
  mockUser10,
];
